# Generated by Django 3.1.6 on 2021-02-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blog_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
            preserve_default=False,
        ),
    ]
